### ISSUE TITLE
Add authentication system to distinguish between user roles

### ISSUE THREAD

**Issue by nii236** [perthgophers/puddle#19]

**Comment by AlexDunmow** [comment]
authentication not necessary, as authentication is handled by Slack itself

**Comment by nii236** [comment]
This is regarding GPG register, auth, verify phases

**Comment by AlexDunmow** [comment]
What would we need this for though? For example, wouldn't a command coming from @nii236 only be from you?

**Comment by nii236** [comment]
Yeah agree, no real use case for this (yet)
